excluded:
  - Pods

# Keep pragmatic thresholds for this SwiftUI-heavy project
line_length:
  warning: 180
  error: 220
  ignores_comments: true
  ignores_urls: true
  ignores_interpolated_strings: true

# SwiftUI ergonomics and pragmatic thresholds
disabled_rules:
  - multiple_closures_with_trailing_closure
  - orphaned_doc_comment
  - no_fallthrough_only

function_body_length:
  warning: 120
  error: 170

type_body_length:
  warning: 400
  error: 600

file_length:
  warning: 500
  error: 800
